#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8333
#  thymeleaf:
#    cache: false
#  application:
#    name: gulimall-seckill
#  session:
#    store-type: redis
#    timeout: 3600
#  redis:
#    host: gulimall.com
#  task:
#    execution:
#      pool:
#        max-size: 50
#        core-size: 5
#  rabbitmq:
#    host: gulimall.com
#    virtual-host: /
#    publisher-confirms: true
#    publisher-returns: true
#    template:
#      mandatory: true
#    #消费端手动确认ack
#    listener:
#      simple:
#        acknowledge-mode: manual
#server:
#  port: 7011
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
