#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: query_route_test
#          uri: https://www.baidu.com/
#          predicates:
#            - Query=url,baidu
#        - id: oss_route
#          uri: lb://gulimall-third-party
#          predicates:
#            - Path=/api/thirdparty/**
#          filters:
#            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}
#        - id: product_route
#          uri: lb://gulimall-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#        - id: member_route
#          uri: lb://gulimall-member
#          predicates:
#            - Path=/api/member/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#        - id: ware_route
#          uri: lb://gulimall-ware
#          predicates:
#            - Path=/api/ware/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
#
#        - id: product_host_route
#          uri: lb://gulimall-product
#          predicates:
#            - Host=gulimall.com,item.gulimall.com
#
#        - id: auth_host_route
#          uri: lb://gulimall-auth-server
#          predicates:
#            - Host=auth.gulimall.com
#
#        - id: search_host_route
#          uri: lb://gulimall-search
#          predicates:
#            - Host=search.gulimall.com
#  application:
#    name: gulimall-gateway
#
